import type { Metadata } from "next";
import { Geist, Geist_Mono, Battambang } from "next/font/google";
import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const khmerFont = Battambang({
  weight: ['400', '700'],
  subsets: ['khmer'],
  display: 'swap',
  variable: '--font-khmer',
});

export const metadata: Metadata = {
  title: {
    default: "My App",
    template: "%s - MR.LUBE",
  },
  description: "Generated by create next app",
  icons: {
    icon: "/Logo-favicon.png",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale} className={`${khmerFont.variable} ${geistSans.variable} ${geistMono.variable}`}>
      <body
        className={`${khmerFont.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
